# Generated by Django 4.1.4 on 2022-12-23 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_yyy_position_robot_y_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaur',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_dinosaur', to='core.game'),
        ),
    ]
